name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
        dotnet build --configuration Debug
        dotnet build --configuration Release
      
    - name: Upload debug build
      uses: actions/upload-artifact@v4
      with:
        name: debug
        path: |
          bin/Debug/net4.6.1/FTD2XX_NET.dll

    - name: Upload release build
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: |
          bin/Release/net4.6.1/FTD2XX_NET.dll
